# Generated by Django 5.2 on 2025-12-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('store_image', models.ImageField(blank=True, null=True, upload_to='store_images/')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('aspect_ratio', models.CharField(default='16:9', max_length=20)),
                ('resolution', models.CharField(default='720p', max_length=20)),
                ('negative_prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='generated_videos/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
